### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by nsfreak** [ruddell/generator-jhipster-ionic#2]
Missing module after running command **yo jhipster-ionic --force** in empty folder

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\generator-jhipster-ionic\generators\app\index.js:6:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

OS: Win 10
node: v4.2.3
npm: 2.15.6 / 3.8.2   (tested with both)

**Comment by nsfreak** [comment]
after installing module fs-extra (npm install --g fs-extra) jhip-ionic started.

**Comment by ruddell** [comment]
I needed to add it to dependencies in the package.json.  Thanks for the catch!
