### ISSUE TITLE
JHipster Ionic Generator Exception

### ISSUE THREAD

**Issue by huiqiangyang** [ruddell/generator-jhipster-ionic#30]
Hello my friends, I need your help ,today I want to use JHipster Ionic Generator , when I geneator code,show this error
```shell
Files will be generated in folder: /home/yhq/pro1612/hui-app
? Where is the parent directory of the JHipster monolith/gateway located ? ../
1 applications found at /home/yhq/pro1612/
? Which application do you want to generate from? hui-web
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn cordova ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) 
```
My system is Ubuntu,node version v6.9.2 ,npm version 4.1.1, Jhipster version latest
Could you tell me a method to solve this question,thank you~!

**Comment by dimeros** [comment]
Are you sure that you execute the command:  npm install -g ionic yo bower gulp generator-m-ionic cordova without any problem?

**Comment by huiqiangyang** [comment]
where I execute this command show many warn,tell me version is too low may me failed, but I don't know how to update these plugins. my npm & node & yo is latest version.

**Comment by ruddell** [comment]
What does running `cordova` say? It looks like you don't have it installed.

**Comment by huiqiangyang** [comment]
Thank you ! I think it's main reason, because if I genator code choose gulp test it also show this error, I think may be my npm plugin has version error
